LOAD DATA LOCAL INFILE 'bid0.dat' INTO TABLE bid FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
LOAD DATA LOCAL INFILE 'seller0.dat' INTO TABLE seller FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
LOAD DATA LOCAL INFILE 'item0.dat' INTO TABLE item FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
LOAD DATA LOCAL INFILE 'bider0.dat' INTO TABLE bider FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
LOAD DATA LOCAL INFILE 'location_item0.dat' INTO TABLE location_item FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
LOAD DATA LOCAL INFILE 'categ0.dat' INTO TABLE categ FIELDS TERMINATED BY ' |*| ' LINES TERMINATED BY "\n";
