LOAD DATA LOCAL INFILE 'item0.csv' INTO TABLE item FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'seller0.csv' INTO TABLE seller FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'bider0.csv' INTO TABLE bider FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'location_item0.csv' INTO TABLE location_item FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'categ0.csv' INTO TABLE categ FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'bid0.csv' INTO TABLE bid FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

